### ISSUE TITLE
Questions about data split

### ISSUE THREAD

**Issue by atusi-nakajima** [Deepthi-Jallepalli/CMPE-295A-Master-Project#1]
Thank you for providing the code.
I am trying to reproduce it with reference to Steps to Reproduce, but the data split is not working. Here is the error What should I do?

Traceback (most recent call last):
  File "dataset/data_split.py", line 12, in <module>
    f = open('/home/014352130/fl_project/kitti_train_backup.txt')
FileNotFoundError: [Errno 2] No such file or directory: '/home/014352130/fl_project/kitti_train_backup.txt'

**Comment by navyacr** [comment]
This is my local path for the kitti train dataset. Please update the relevant path here to proceed further. You can download the kitti train dataset from the official website and update the path in the code.

**Comment by atusi-nakajima** [comment]
Thank you for your reply.
Please let me know if there are a few things I don't understand.
Currently I have downloaded the dataset from the official kitti website. (The two files I downloaded are as follows. Is this correct?
[on this site](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark)
・Download left color images of object data set (12 GB) (data_object_image_2.zip)
・Download training labels of object data set (5 MB) (data_object_label_2.zip))

Then I extracted them in the same directory.
The directory structure is as follows
.
├── testing
│   　　└── image_2
└── training
   　　 　├── image_2
   　　　 └── label_2


How can I then convert the data to yolo and do the data split?
I checked the code in data_split.py, but I don't think it includes the conversion to yolo.
Could you please explain in as much detail as possible the steps for converting to yolo and data split?
Thank you in advance.
